### ISSUE TITLE
Git Naming Conventions

### ISSUE THREAD

**Issue by user2745** [IoTresor/geo-api#19]
Git Naming Conventions for this project:

General Format:
< type >(< scope >): < subject >

< body >

< footer >

[More Information](https://karma-runner.github.io/4.0/dev/git-commit-msg.html)

**Comment by dgatto** [comment]
I can do some research and see if there are pre-defined conventions for this.

**Comment by user2745** [comment]
Let me know your thoughts on this:
https://karma-runner.github.io/4.0/index.html
https://karma-runner.github.io/4.0/dev/git-commit-msg.html

**Comment by dgatto** [comment]
I like their example message. It seems more tailored to commit messages rather than pull requests, tho.

Here’s a couple more resources I found. We can pick and choose from all of these to see what works for us.

https://github.com/segunolalive/helloBooks/wiki/Pull-request-Naming-and-Description-Convention

I really like this one too especially: https://namingconvention.org/git/pull-request-naming.html
